export const INDEX_SCREEN = "/";
export const HOME_SCREEN = "home";
export const HOME_MAP_SCREEN = "home/map";
export const HOME_SCOUT_REPORT_SCREEN = "home/scout-report";
export const HOME_SETTINGS_SCREEN = "/home/settings";
export const HOME_FEEDBACK_SCREEN = "/home/feedback";
export const HOME_FIELD_UPLOAD_SCREEN = "/home/field-upload";
export const SCOUT_CREATE_REPORT_SCREEN = "/scout-report/create";
export const SCOUT_REPORT_EDIT_SCREEN = "/scout-report/[slug]";
export const MAP_DRAW_SCREEN = "map-draw";
export const LOGIN_SCREEN = "/login";
export const SIGNUP_SCREEN = "/signup";
export const INFO_LANDING_SCREEN = "/info/landing";
export const INFO_PRODUCTS_SCREEN = "/info/products";
export const INFO_ABOUT_SCREEN = "/info/about";
export const INFO_CONTACT_SCREEN = "/info/contact";
export const INFO_PRICING_SCREEN = "/info/pricing";
export const SETTINGS_MANAGE_GROWERS_SCREEN = "/home/settings/manage-growers";
export const SETTINGS_MANAGE_ORGANIZATION_SCREEN =
  "/home/settings/manage-organization";
export const SETTINGS_MANAGE_CROPS_SCREEN = "/home/settings/manage-crops";
export const SETTINGS_MANAGE_PESTS_SCREEN = "/home/settings/manage-pests";
export const SETTINGS_MANAGE_WEEDS_SCREEN = "/home/settings/manage-weeds";
export const SETTINGS_MANAGE_DISEASES_SCREEN = "/home/settings/manage-diseases";
export const SETTINGS_MANAGE_INSECTS_SCREEN = "/home/settings/manage-insects";

export const VERIFICATION_EMAIL_PROMPT_SCREEN = "/verify/prompt";
export const VERIFICATION_EMAIL_SUCCESS_SCREEN = "/verify/success";
export const VERIFICATION_EMAIL_FAILURE_SCREEN = "/verify/failure";
